### ISSUE TITLE
 test de plugin

### ISSUE THREAD

**Issue by limad** [eliovir/rust-examples#8]
**Salut**
peut tu me contacter en MP via community.
... test de plugin

**Comment by eliovir** [comment]
Salut Limad,

Je n'ai pas trouvé ton compte sur https://users.rust-lang.org/.

**Comment by limad** [comment]
Salut
Désolé je t'es contacté via ce repo par hasard je n'est pas de compte rust.
C'était pour savoir si ça t'intéresse de tester le plugin helloWatt Jeedom.
Bonne soirée
